--- a/src/Makefile
+++ b/src/Makefile
@@ -1,5 +1,5 @@
 CFLAGS += -I../include
-LDLIBS += -lgfortran -lrt -Wl,-Bstatic -lgsl -lopenblas -Wl,-Bdynamic -fopenmp
+LDLIBS += -lgfortran -lrt -Wl,-Bdynamic -fopenmp -llapacke -llapack -lgsl -lopenblas -lm
 
 ifeq ($(OPTIMIZE), 1)
        CFLAGS += -O2
